<?php

/**
 * @file
 * Functions to support theming in the Adminimal theme.
 */

use Drupal\Core\Form\FormStateInterface;

// Change submit button on entity browser
function cotailored_adminal_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  if (in_array($form_id, ['entity_browser_browse_files_modal_form', ])) {
    $form['widget']['actions']['submit']['#value'] = t('Select files');
  }
}